### PR TITLE
add custom resolution support

### PR DESCRIPTION
**Pull request by Volkanite**
Adds support for custom resolutions. Can help users with 16:10 aspect ratio displays as the game doesn't support these by default. Code checks NFSMWExtraOptionsSettings.ini for custom resolution's width and height.

### CODE REVIEW

**Comment by DiamondMaster07** [comment]
Shouldn't this go to the ws fix? Also what do you mean by 16:10 support? Afaik with the ws patch, 16:10 works perfectly with HUDWidescreenMode=0. Also RockportEd adds a resizable windowed mode option(check NFSMods.xyz for it)

**Comment by Volkanite** [comment]
@DiamondMaster07 you are right. I discovered the WidescreenFixesPack only after i made this. So i guess there isn't any need for this. Would still be awesome if NFSMWExOpts had it's own resolution support though. Also the ws patch with 16:10 isn't exactly perfect as setting HudWidescreenMode=0 brings the map and speedometer too close to the car for my liking. **I'm not saying this commit fixes that issue for 16:10** i'm just saying it's not perfect.

But thanks for the suggestions. I'll leave it open for the maintainers to look over it and close it if they see fit.

**Comment by nlgzrgn** [comment]
Hi! Nice work you did there, but unfortunately I don't want to add this in Extra Options; because custom resolution selection is already available in Widescreen Fix by ThirteenAG.

I'm also trying to see what we can do about HUD with 16:10, 5:4, 21:9 like crop aspect ratios. I want to make a seperate script that works together with Widescreen Fix. I think I'll also add some more options in it.

Anyways, here is a mockup I've done more than a year ago (NFSMW in 21:9)
resim

**Comment by Volkanite** [comment]
> Nice work you did there, but unfortunately I don't want to add this in Extra Options; because custom resolution selection is already available in Widescreen Fix by ThirteenAG.

@nlgzrgn  I fully understand.

And the work you've done so far looks awesome. I'll be looking into a perfect 16:10 HUD myself also until yours is completed. You can close this PR.

**Pull request closed without merging**
